### ISSUE TITLE
General: Heading 1  to 6 should have a font weight of normal / 400 since font is already bold.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#21]

**Comment by nakul-titan** [comment]
Font weight is normal already.

![font-weight-normal](https://cloud.githubusercontent.com/assets/13461911/9734416/78276e6e-5650-11e5-8001-d19574269d87.jpg)

**Comment by ermatitan** [comment]
I have check each header on the site and all of them has a font weight of 500, which should be 400/normal

![image](https://cloud.githubusercontent.com/assets/12791909/9778477/6a9a2580-57a3-11e5-8da1-0653ab87f77e.png)

**Comment by nakul-titan** [comment]
When it is set to normal in the code, as you can in see the screenshot i have attached, normal font-weight will only get applied. The one which you have marked is the style  property specified by Bootstrap. 

You can check by changing that to normal or 400, you wont see any difference. What im trying to explain you is: "Currently normal font weight is applying to it as i have added the style property "font-weght: normal;" to that font family while installing it in the website"

Hope this make sense :)

Thanks

**Comment by ermatitan** [comment]
Hello Nakul, 

The code and the computed css should coincide maybe. Changing the font-weight to 400 has a lot of difference. This has been fix by all other sites and hope you can fix it too. Thanks
