### ISSUE TITLE
News Single Page - Breadcrumbs should be displayed below the post/page title as per standard.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#22]
knowledgebase standard:
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/breadcrumbs

![image](https://cloud.githubusercontent.com/assets/12791909/9674976/171cd320-52ea-11e5-92b3-aec65d870113.png)

**Comment by nakul-titan** [comment]
As per the design breadcrumbs should be above the title, but as per standard its different. In this case the designer who is making the website designs should be aware of it. We are hopping this message could be passed to concerned person. Thanks :)

**Comment by ermatitan** [comment]
This issue have been brought up to the concerned person as per Bernard. As for now we should follow the standard. Thanks
