### ISSUE TITLE
SEO Footer : Please specify what SEO footer to use.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#29]
https://knowledgebase.titanweb.com.au/development/updating-the-footer-for-seo-ranking

**Comment by nakul-titan** [comment]
None of the given cases matched design, so i took the 1st case and edited it to meet the requirement.

**Comment by ermatitan** [comment]
Please choose to any of the code on the link  to meet the SEO standard and logo use the new "TitanWeb" logo and link to http://www.titanweb.com.au/. Thanks

https://knowledgebase.titanweb.com.au/development/updating-the-footer-for-seo-ranking

**Comment by nakul-titan** [comment]
I have changed it as you said. Earlier i just developed it as in the design and also used SEO footer technique. So the change you asked would be comes under "Enhancement" if im not wrong.

Kindly change the label to Enhancement.

Thanks

**Comment by ermatitan** [comment]
I have checked each SEO footer code and none of them  match the footer in the site. Maybe the fix has not been push through. Please check
