### ISSUE TITLE
General-Mobile : Featured image should be aligned centered in all smaller devices via portrait view (S4,iTouch)

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#37]
S4, iTouch

![image](https://cloud.githubusercontent.com/assets/12791909/9677805/fec97b1c-5310-11e5-9428-6dc88aa45167.png)

**Comment by ermatitan** [comment]
Featured image should also be centered in news - single page.

**Comment by nakul-titan** [comment]
I took care of it along with the listing page featured image. Its already centered. Please check once again. Thanks
