### ISSUE TITLE
Privacy Policy does not meet the standard generic privacy policy layout.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#43]
See Standard here: https://knowledgebase.titanweb.com.au/resource-information/generic-privacy-policy

![image](https://cloud.githubusercontent.com/assets/12791909/9678570/43635c54-5319-11e5-9a89-3f54133f3ca3.png)

**Comment by nakul-titan** [comment]
As per this website prototype list items should have 2 column layout.

**Comment by ermatitan** [comment]
As per conversation about this issue, all ordered list should not be listed on 2 columns since it can hinder the readability of the article. 

It also clear in the design (Our Product page) that only Unordered list where listed in 2 columns. 

There is  a standard design for Privacy Policy page on knowledgebase that need to be strictly implemented. Thanks

**Comment by nakul-titan** [comment]
I have fixed the issue but im not sure which "Our Product page" are you talking about in which only unordered list were listed in 2 columns. 

In the supplied designs i haven't found any page in which only unordered list were listed in 2 columns and ordered list were in single column.

Thanks

**Comment by ermatitan** [comment]
not fix
