### ISSUE TITLE
Product Single : Add to cart button should be disabled to prevent further errors on the cart option

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#47]
![image](https://cloud.githubusercontent.com/assets/12791909/9679357/8d3397fc-5320-11e5-8016-eeb4bbc32663.png)

**Comment by nakul-titan** [comment]
Hi Erma

This is a product catalogue with order form. We have been told by Jolene to style till the checkout page. If we disable the Add to cart button, then customer cant go to the Checkout page. But if you dont want to see the Add to cart button you can just give the price empty to the product.

Thanks

**Comment by bernardtitan** [comment]
There is no documentation that states this is required for this project.
