### ISSUE TITLE
News Single Page : ordered and unordered list were displayed in two columns

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#48]
![image](https://cloud.githubusercontent.com/assets/12791909/9679598/869bfffe-5322-11e5-88a2-2263d4ce901e.png)

**Comment by nakul-titan** [comment]
List items were displaying in two columns as per the design provided. Please have a look at the "About us page design".

**Comment by ermatitan** [comment]
All Ordered list should not be displayed on two columns as it hinders the readability of the article.

**Comment by ermatitan** [comment]
not fix
