### ISSUE TITLE
Product Single Page: Arrow up and down button for quantity box is cut. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#55]
![image](https://cloud.githubusercontent.com/assets/12791909/9779226/1947d9ee-57ac-11e5-9ff0-95dc53e5ab18.png)

**Comment by nakul-titan** [comment]
Hi Erma,

Its not actually cut. Its default browser styling for input type number. I dont think we have to style it as Jolene said do minimum/basic styling for cart, check out pages for catalog websites.

Thanks.

**Comment by ermatitan** [comment]
wont fix. Browser issue
