### ISSUE TITLE
Newly added product does not display as featured products on homepage.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Siteware-Direct#67]
As per CMS user guide: Most recent
![image](https://cloud.githubusercontent.com/assets/12791909/9922807/6d11aec4-5d1f-11e5-9dab-4d7fc37cbafb.png)

I have deleted all previous product (for clean up purposes and added a new set of product and it doesn't automatically set as featured image.

![image](https://cloud.githubusercontent.com/assets/12791909/9922823/b0d4763c-5d1f-11e5-8d79-9a9610ac283b.png)

**Comment by nakul-titan** [comment]
Sorry, its my mistake. We have to manually mark the products as featured. I have updated the user guide.
